### ISSUE TITLE
启动后访问,会在浏览器显示vuex的错误

### ISSUE THREAD

**Issue by tangyuxian** [RainManGO/vue3-composition-admin#110]
Failed to compile.

./node_modules/vuex/dist/vuex.esm-browser.js 132:14-25
"export 'effectScope' was not found in 'vue'

**Comment by RainManGO** [comment]
vue 版本不对

**Comment by RainManGO** [comment]
依赖版本的问题

**Comment by toupil111** [comment]
确实 vuex哪里我选了4.1就会出现问题，选第二个版本就ok了
