### ISSUE TITLE
README 中说的 vue-vue-i18n-next 地址引用错误

### ISSUE THREAD

**Issue by M69W** [RainManGO/vue3-composition-admin#45]
[README](https://github.com/RainManGO/vue3-composition-admin/blob/main/README.md#highlight) 中 的 vue next 系列 描述的 [vue-vue-i18n-next](https://github.com/panter/vue-i18next) 没有 ["vue-i18n": "^9.0.0-beta.16"](https://github.com/RainManGO/vue3-composition-admin/blob/main/package.json#L53)

应该是 这个 [intlify/vue-i18n-next](https://github.com/intlify/vue-i18n-next/)  > [9.0.0-beta.16](https://github.com/intlify/vue-i18n-next/releases/tag/v9.0.0-beta.16)

**Comment by RainManGO** [comment]
是的哦，写错了，欢迎pr修复。

**Comment by M69W** [comment]
另外，切换语言后element-plus的日期没有切换还是英文

**Comment by M69W** [comment]
另外，有个疑问，
既然代码仓库已经转到你这里，
文档仓库还是原来的地址？
似乎没有继续更新？



方便建一个群不？

**Comment by RainManGO** [comment]
已建群，在readme里面，群里交流吧。
