### ISSUE TITLE
图标资源找不到

### ISSUE THREAD

**Issue by myloveCc** [RainManGO/vue3-composition-admin#59]
为啥你这个版本里面没有图标资源，图标又都能显示？

**Comment by zhuanghongbin** [comment]
> 为啥你这个版本里面没有图标资源，图标又都能显示？

同问

**Comment by zhuanghongbin** [comment]
@myloveCc  作者是通过在index.html中直接引入外部icon文件。[#55](https://github.com/RainManGO/vue3-composition-admin/issues/55)

**Comment by myloveCc** [comment]
@zhuanghongbin 原来如此，感谢。

**Comment by myloveCc** [comment]
我在这里找到了一种离线使用svg的方法 https://github.com/wild-sky/vue_ts_svg-sprite-loader 亲测可用。
@RainManGO @zhuanghongbin

**Comment by zhuanghongbin** [comment]
> 我在这里找到了一种离线使用svg的方法 https://github.com/wild-sky/vue_ts_svg-sprite-loader 亲测可用，毕竟不是所有项目部署环境都能访问外网。
> @RainManGO @zhuanghongbin

目前用vite2改造这项目，那个vue_ts_sprite-loader不太用得上了
