### ISSUE TITLE
多级菜单鼠标离开不收起。需要鼠标逐一hover后才收起。

### ISSUE THREAD

**Issue by HealerLZH** [RainManGO/vue3-composition-admin#63]
![image](https://user-images.githubusercontent.com/47292107/117272907-3607c500-ae8e-11eb-8294-4c1c0b1a5346.png)

我自己做的项目中也存在这个问题，请问您有什么解决方案吗

**Comment by ComponentTY** [comment]
将el-submenu的  popper-append-to-body  改为false ， 或者不设置这个属性走默认的就好了

**Comment by ComponentTY** [comment]
> ![image](https://user-images.githubusercontent.com/47292107/117272907-3607c500-ae8e-11eb-8294-4c1c0b1a5346.png)
> 
> 我自己做的项目中也存在这个问题，请问您有什么解决方案吗


你好，
     根据你的问题描述， 可以将el-submenu的 popper-append-to-body 改为false ， 或者不设置这个属性走默认的就好了
