### ISSUE TITLE
是否支持 babel7的可选链配置?

### ISSUE THREAD

**Issue by atom-7** [RainManGO/vue3-composition-admin#68]
写代码经常遇到,需要用到可选链,但是可选链配置是基于 babel7 在网上找了很多文档都无法检测出,这个项目的babel是不是7的,想问一下作者这个babel属于哪本版本的

**Comment by RainManGO** [comment]
看package.json  babel-loader 是8.2.2 最新的，支持babel7.x
https://www.npmjs.com/package/babel-loader
