### ISSUE TITLE
Cannot find module 'fork-ts-checker-webpack-plugin-v5'

### ISSUE THREAD

**Issue by asyncTime** [RainManGO/vue3-composition-admin#80]
ERROR  Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
- E:\webpack\vue3-composition-admin\node_modules\_@vue_cli-plugin-typescript@4.5.13@@vue\cli-plugin-typescript\index.js
- E:\webpack\vue3-composition-admin\node_modules\_@vue_cli-service@4.5.13@@vue\cli-service\lib\Service.js
- E:\webpack\vue3-composition-admin\node_modules\_@vue_cli-service@4.5.13@@vue\cli-service\bin\vue-cli-service.js

**Comment by RainManGO** [comment]
cli或者npm 问题吧，自己百度下。看readme ,推荐用yarn
