### ISSUE TITLE
resetRouter是否是多余的函数？

### ISSUE THREAD

**Issue by lianglixiong** [RainManGO/vue3-composition-admin#84]
路由模块（\vue3-composition-admin\src\router\index.ts）这个路径下有
```js
export function resetRouter() {
     const newRouter = router;
     (router as any).matcher = (newRouter as any).matcher // reset 
}
```
这个函数，一直看不懂有啥用 能介绍下么

我找了一下文档也没看到matcher 这个东西 打印也是undefined

**Comment by sun-scy** [comment]
退出登录时，经过新建一个全新的 Router，而后将新的 Router.matcher 赋给当前页面的管理 Router，以达到更新路由配置的目的。
