### ISSUE TITLE
为什么用npm install也跑不起来呢

### ISSUE THREAD

**Issue by fishcanotfly** [RainManGO/vue3-composition-admin#86]
这样的引入方式应该完全没毛病，但是就是报错了，跑不起来
![image](https://user-images.githubusercontent.com/49266993/128999917-4969e050-c2e1-46c3-87ac-6a8bd4fb69f2.png)

**Comment by fishcanotfly** [comment]
崩溃，用yarn也跑不起来...

**Comment by fishcanotfly** [comment]
最新版本应该哪里有问题，我估计是提交漏了。 学习的话，下之前的一个版本 ，基本没啥大问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RainManGO/vue3-composition-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 凌晨5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RainManGO/vue3-composition-admin] 为什么用npm install也跑不起来呢 (#86)





 
一样
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RainManGO** [comment]
这个问题是因为升级了3.2.2，npm安装的时候自动更新了。项目支持的是3.0.5，最新版本应该没有问题了，上传了锁定包文件。
